# Generated by Django 4.0.4 on 2022-05-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('site', models.TextField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('category', models.CharField(max_length=30)),
            ],
        ),
    ]
