# Generated by Django 4.0.4 on 2022-05-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0002_alter_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='sub_category',
            field=models.CharField(default='Non', max_length=30),
            preserve_default=False,
        ),
    ]
