# Generated by Django 4.0.4 on 2022-09-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0002_alter_store_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='site',
            field=models.TextField(unique=True),
        ),
    ]
