# Generated by Django 4.0.4 on 2022-05-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0003_store_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='sub_category',
            field=models.TextField(),
        ),
    ]
