# Generated by Django 4.0.4 on 2022-09-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.TextField()),
                ('price', models.TextField()),
                ('detail', models.TextField(unique=True)),
            ],
        ),
    ]
